### data preprocessing

##### import libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 

##### importing the dataset 

In [2]:
dataset=pd.read_csv('Data.csv')
# create ntwo new entities - materic or features  and second ----dependent variable vector
# features are the columns using which we are doing to predict the dependent variable or outcome 
# features also called as independent variable 

x = dataset.iloc[:, :-1].values # taken alll the rows
# x- feature column
#iloc= locate index- takes index of row /column which we need to extrct 
# :   --> will take all the rows
#  :-1 ----> python exclude the last values (n), so here exctly sice x is input / featue , it will take all feature columns except the outputcolumn  
# : refers range

y=dataset.iloc[:,-1].values
# we need single column so we removed : (range) from column
print(x,y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]] <StringArray>
['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
Length: 10, dtype: str


##### taking care of missing values

In [3]:
# filling missing values by average 
# using scikit learn to handle missing values 
from sklearn.impute import SimpleImputer
imputer_obj = SimpleImputer(missing_values =np.nan,strategy='mean')
imputer_obj.fit(x[:,1:3])# x numerical data
# 1 -- age , 2 --- sal 

x[:,1:3]=imputer_obj.transform(x[:,1:3]) 

In [4]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


##### encoding categorical data

In [5]:
# coverting category into numbers  using one hot encoding 
#turning country column into three columns with binary values
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('enocoder',OneHotEncoder(),[0])] , remainder='passthrough')
# remainder - passthrough --> this is implemetd because we have age and category , we need in the dataset 
# if its not implemeted it will keep only country  with binary value
#remainder='passthrough' keeps the remaining columns (Age, Salary, Purchased) unchanged.
x= np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


#### encoding the independent variable

In [6]:
# using label encoder

from sklearn.preprocessing import LabelEncoder
le= LabelEncoder() # y has only one column
y =le.fit_transform(y)
# no need to call numpy  because depyendent column 

print(y)

[0 1 0 0 1 1 0 1 0 1]


In [7]:
# Importing the necessary libraries


# Load the dataset


# Identify the categorical data


# Implement an instance of the ColumnTransformer class


# Apply the fit_transform method on the instance of ColumnTransformer


# Convert the output into a NumPy array


# Use LabelEncoder to encode binary categorical data


# Print the updated matrix of features and the dependent variable vector



#### encoding the dependent variable

In [8]:
# using label encoder

from sklearn.preprocessing import LabelEncoder
le= LabelEncoder() # y has only one column
y =le.fit_transform(y)
# no need to call numpy  because depyendent column 

print(y)

[0 1 0 0 1 1 0 1 0 1]


#### splitting the dataset into training set and test set 

In [9]:
# function from sklearn  - train_test_split

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=1)

In [10]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [11]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [12]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [13]:
print(y_test)

[0 1]


In [14]:
# Import necessary libraries

# Load the Iris dataset

# Separate features and target

# Split the dataset into an 80-20 training-test set

# Apply feature scaling on the training and test sets

# Print the scaled training and test sets

## feature scaling

#### wedo feature scaling  so that one feature do not dominate other feature 

In [15]:
# Feature scaling is applied after splitting the dataset to prevent data leakage.

# What is Data Leakage?

# Data leakage happens when information from the test set indirectly influences the training process.

# If scaling is done before splitting, the scaling method calculates values like:

# mean
# standard deviation
# minimum
# maximum

# using the entire dataset, including the test data.

# This gives the model indirect knowledge about the test set, which is incorrect.

# Correct Order
# Import dataset
# Handle missing values
# Encode categorical data
# Split into training and test set
# Apply feature scaling

In [16]:
# keeping all the features in same scale 

#### how feature scaling is applied or implemented??

##### using 2 methids --> standardisation and normalization
##### standardisation ----> x-mean(x)/sd(x)   range --> can be ussed on all dataset
##### normalization ----> x= x-min(x)/max(x)-min(x)    range 

In [17]:
# standard scalerfrom 
from sklearn.preprocessing import StandardScaler
sdc= StandardScaler() #no arguments neded to pass 

# x -- only numerial values and 3: age and all
x_train[:,3:]=sdc.fit_transform(x_train[:,3:])#ntaking oly numerical columns 

# similar;y doing or x_test , but for x_test we will not  qgqin apply scaler method 
# because it is test set , it should get the scaled values on training only 
# if scaler applied on test, it will create a new scaler value 
# apply same scler on test set which was applied on train set 
x_test[:,3:]=sdc.fit_transform(x_test[:,3:])


# fit = will get mean /average and sd from all features (formula) , and tranfrom will apply the formula so thta they can be at same scale 


print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [18]:
print(x_test)

[[0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 1.0 1.0]]


# Regression

## SIMPLE LINEAR REGRESSION

** Simple Linear Regression is a Machine Learning algorithm used to predict a continuous numerical value using only one independent variable (input feature).

 tries to find best fit  straight line

  y^ = bo +b1x1

  y^^--> dependent variable / outcome
  bo--> y - intercept (constant)
  b1 --> clope coefficient
  x1 --> independent variable( input /fetaures)

  simple linear regression 


In [19]:
# Simple linear regression is a statistical method used to model the relationship between one independent variable (X) and one dependent variable (Y) by fitting a straight line to observed data.